app = "calabi"
primary_region = "den"

[build]

[env]
RUST_LOG = "debug,hyper=info,reqwest=warn,rustls=warn,h2=warn"

[http_service]
internal_port = 8080
protocol = "tcp"
auto_stop_machines = false
auto_start_machines = false
min_machines_running = 1
